PL/Controllers/AseguradoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AseguradoraController : Controller
    {

        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result();
            result = BL.Aseguradora.GetAll();

            if (result.Correct)
            {
                ML.Aseguradora aseguradora = new ML.Aseguradora();
                aseguradora.Aseguradoras = result.Objects;
                return View(aseguradora);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Form(int? IdAseguradora)
        {
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            aseguradora.Usuario = new ML.Usuario();
            aseguradora.Usuario.Rol = new ML.Rol();

            ML.Result resultUsuario = BL.Usuario.GetAll(aseguradora.Usuario);


            if (IdAseguradora == null)
            {
                aseguradora.Usuario.Usuarios = resultUsuario.Objects;
                return View(aseguradora);
            }
            else
            {
                //GetbyId
                ML.Result result = BL.Aseguradora.GetById(IdAseguradora.Value);

                if (result.Correct)
                {
                    aseguradora = (ML.Aseguradora)result.Object;
                    aseguradora.Usuario.Usuarios = resultUsuario.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar la aseguradora seleccionada";
                }
                return View(aseguradora);
            }

        }

        [HttpPost]
        public ActionResult Form(ML.Aseguradora aseguradora)
        {

            ML.Result result = new ML.Result();

            if (aseguradora.IdAseguradora == 0)
            {
                //add
                result = BL.Aseguradora.Add(aseguradora);

                if (result.Correct)
                {
                    ViewBag.Message = "Se ha registrado La Aseguradora";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "No ha registrado la Aseguradora" + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
            else
            {
                //update
                result = BL.Aseguradora.Update(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = "Se ha Actualizado El Registro";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "No ha Actualizado El Registro " + result.ErrorMessage;
                    return PartialView("Modal");
                }

            }
        }

        [HttpGet]
        public ActionResult Delete(int IdAseguradora)
        {
            ML.Result result = new ML.Result();
            result = BL.Aseguradora.Delete(IdAseguradora);

            if (result.Correct)
            {
                ViewBag.Message = "Se ha elimnado el registro";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Message = "No se ha elimnado el registro" + result.ErrorMessage;
                return PartialView("Modal");
            }
        }
    }
}

PL/Views/Aseguradora/Form.cshtml
@model ML.Aseguradora
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Form</h2>
    <div class="row">

        <div class="col-md-12">

            @using (Html.BeginForm("Form", "Aseguradora", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdAseguradora, new {  style="display: none;" })

                            @Html.TextBoxFor(model => model.IdAseguradora, new { style="display: none;" ,@class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdAseguradora)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Nombre)

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Nombre)

                        </div>


                    </div>
                 

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Usuario.IdUsuario)

                            @Html.DropDownListFor(model => model.Usuario.IdUsuario, new SelectList(Model.Usuario.Usuarios, "IdUsuario", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Usuario.IdUsuario)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>

                    </div>

                </div>

            }

        </div>

    </div>
</div>

PL/Views/Aseguradora/GetAll.cshtml
@model ML.Aseguradora
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Aseguradora</h2>
    <p>Aqui puede ver, editar o agrgar a un Aseguradora</p>
    <p>Para agregar un Aseguradora presione el boton verde</p>
    <p>Para editar un Aseguradora presione el boton amarillo</p>
    <p>Para eliminar un Aseguradora presione el boton rojo</p>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <hr />

    <div class="row">

        <table class="table  table-hover table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Editar</th>
                    <th style="display:none;">IdAseguradora</th>
                    <th>Nombre</th>
                    <th>Fecha Creacion</th>
                    <th>Fecha De Modificacion</th>
                    <th>Usuario</th>
                    <th>Eliminar</th>
                </tr>

            </thead>
            <tbody>
                @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                {
                    <tr>
                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-warning" href="@Url.Action("Form", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })"><i class="bi bi-pencil-square" style="color: ivory"></i></a></td>
                        <td style="display: none;">@aseguradora.IdAseguradora</td>
                        <td>@aseguradora.Nombre </td>
                        <td>@aseguradora.FechaCreacion</td>
                        <td>@aseguradora.FechaModificacion</td>
                        <td>@aseguradora.Usuario.Nombre</td>

                    <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger" href="@Url.Action("Delete", "Aseguradora", new { IdAseguradora= aseguradora.IdAseguradora})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-eraser-fill" style="color: mintcream"></i></a></td>


                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

PL/Views/Aseguradora/Modal.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>