PL/Controllers/CargaMasivaController.cs
using Microsoft.AspNetCore.Mvc;
using System.IO;
using ML;

namespace PL.Controllers
{
    public class CargaMasivaController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public CargaMasivaController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public ActionResult UsuarioCargaMasiva()
        {
            ML.Result result = new Result();
            return View(result);
        }

        [HttpPost]
        public ActionResult CargaTXT()
        {
            IFormFile fileTXT = Request.Form.Files["archivoTXT"];

            if (fileTXT != null)
            {

                StreamReader Textfile = new StreamReader(fileTXT.OpenReadStream());
                string line;
                line = Textfile.ReadLine();
                while ((line = Textfile.ReadLine()) != null)
                {
                    string[] lines = line.Split('|');

                    ML.Usuario usuario = new ML.Usuario();

                    usuario.Nombre = lines[0];
                    usuario.ApellidoPaterno = lines[1];
                    usuario.ApellidoMaterno = lines[2];
                    usuario.FechaNacimiento = lines[3];
                    usuario.Sexo = lines[4];
                    usuario.Telefono = lines[5];
                    usuario.Email = lines[6];
                    usuario.UserName = lines[7];
                    usuario.Password = lines[8];
                    usuario.Celular = lines[9];
                    usuario.Curp = lines[10];
                    usuario.Imagen = null;

                    usuario.Rol = new ML.Rol();
                    usuario.Rol.IdRol = int.Parse(lines[11]);

                    usuario.Direccion = new ML.Direccion();
                    usuario.Direccion.Calle = lines[12];
                    usuario.Direccion.NumeroInterior = lines[13];
                    usuario.Direccion.NumeroExterior = lines[14];

                    usuario.Direccion.Colonia = new ML.Colonia();
                    usuario.Direccion.Colonia.IdColonia = int.Parse(lines[15]);

                    ML.Result result = BL.Usuario.Add(usuario);

                    if (!result.Correct)
                    {
                        StreamWriter sw = new StreamWriter("C:\\Users\\digis\\Documents\\JOSE MIGUEL PEREZ JUAREZ\\Error.txt");

                        sw.WriteLine("Existe Un Error " + result.ErrorMessage);
                        sw.Close();
                    }
                    else
                    {
                        ViewBag.Message = "Se Han Registrado los Usuarios";
                    }

                }
            }
            return PartialView("Modal");
        }

        [HttpPost]
        public ActionResult UsuarioCargaMasiva(ML.Usuario usuario)
        {

            IFormFile excelCargaMasiva = Request.Form.Files["FileExcel"];
            //Session 

            if (HttpContext.Session.GetString("PathArchivo") == null) //sesion nula o que no exista 
            {
                //validar el excel

                if (excelCargaMasiva.Length > 0)
                {
                    //que sea .xlsx
                    string fileName = Path.GetFileName(excelCargaMasiva.FileName);
                    string folderPath = _configuration["PathFolder:value"];
                    string extensionArchivo = Path.GetExtension(excelCargaMasiva.FileName).ToLower();
                    string extensionModulo = _configuration["TipoExcel"];

                    if (extensionArchivo == extensionModulo)
                    {
                        //crear copia
                        string filePath = Path.Combine(_hostingEnvironment.ContentRootPath, folderPath, Path.GetFileNameWithoutExtension(fileName)) + '-' + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";
                        if (!System.IO.File.Exists(filePath))
                        {
                            using (FileStream stream = new FileStream(filePath, FileMode.Create))
                            {
                                excelCargaMasiva.CopyTo(stream);
                            }
                            //leer

                            string connectionString = _configuration["ConnectionStringExcel:value"] + filePath;

                            ML.Result resultConvertExcel =  BL.Usuario.ConvertirExceltoDataTable(connectionString);

                            if (resultConvertExcel.Correct)
                            {
                                ML.Result resultValidacion = BL.Usuario.ValidarExcel(resultConvertExcel.Objects);
                                if (resultValidacion.Objects.Count == 0)
                                {
                                    resultValidacion.Correct = true;
                                    HttpContext.Session.SetString("PathArchivo", filePath);
                                }
                                return View("UsuarioCargaMasiva",resultValidacion);
                            }
                            else
                            {
                                //error al leer el archivo
                                ViewBag.Message = "Ocurrio un error al leer el arhivo";
                                return View("Modal");
                            }
                        }
                    }

                }
                //verificar que no tenga errores 
                //le avisamos al usuario que el excel esta mal ML.ErrorExcel 
                //crea la sesion 
            }
            else
            {
                string rutaArchivoExcel = HttpContext.Session.GetString("PathArchivo");
                string connectionString = _configuration["ConnectionStringExcel:value"] + rutaArchivoExcel;

                ML.Result resultData = BL.Usuario.ConvertirExceltoDataTable(connectionString);
                if (resultData.Correct)
                {
                    ML.Result resultErrores = new ML.Result();
                    resultErrores.Objects = new List<object>();

                    foreach (ML.Usuario usuarioItem in resultData.Objects)
                    {

                        ML.Result resultAdd = BL.Usuario.Add(usuarioItem);
                        if (!resultAdd.Correct)
                        {
                            resultErrores.Objects.Add("No se insertó el usuario con nombre: " + usuarioItem.Nombre + " Error: " + resultAdd.ErrorMessage);
                        }
                    }
                    if (resultErrores.Objects.Count > 0)
                    {

                        //string fileError = Path.Combine(_hostingEnvironment.WebRootPath, @"~\Files\logErrores.txt");
                        string fileError = _hostingEnvironment.WebRootPath +  @"\Files\logErrores.txt";
                        using (StreamWriter writer = new StreamWriter(fileError))
                        {
                            foreach (string ln in resultErrores.Objects)
                            {
                                writer.WriteLine(ln);
                            }
                        }
                        ViewBag.Message = "Los usuarios No se han sido registrados correctamente";
                    }
                    else
                    {
                        ViewBag.Message = "Los usuarios se han sido registrados correctamente";

                    }

                }

            }
            return PartialView("Modal");
         }
    }
}

PL/Views/CargaMasiva/Modal.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "UsuarioCargaMasiva", "CargaMasiva", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/CargaMasiva/UsuarioCargaMasiva.cshtml
@model ML.Result
@{
    ViewData["Title"] = "CargaMasiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*<div class="container">
    @using (Html.BeginForm("CargaTXT", "CargaMasiva", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="d-grid gap-2 col-6 mx-auto">
                <button class="btn btn-outline-warning" type="button" onclick="myFunctionTxt()">TXT</button>
                <input type="file" name="archivoTXT" id="InputTxt"/>
                <button class="btn btn-outline-success" type="button" onclick="myFunctionExcel()">Excel</button>
                <input type="file" id="InputExcel" />
            </div>
            <button type="submit" class="btn btn-outline-success" type="button">Cargar</button>
        </div>
    }
</div>*@

<div class="container">
    <h1>Carga Masiva de Usuarios</h1>
    <h5>Seleccione con que tipo de archivo desea hacer la carga</h5>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <a><input type="submit" value="Excel" class="btn btn-success col-md-12" id="xlsx"/></a>
        </div>
        <div class="col-md-6">
            <a><input type="submit" value="TXT" class="btn btn-primary col-md-12" id="txt" /></a>
        </div>
    </div>


 @using (Html.BeginForm("UsuarioCargaMasiva", "CargaMasiva", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="row g-3" id="fuImage" style="display:none;">
        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-file-earmark-text-fill" style="color: lightseagreen"></i></span>
                <input type='file' class="form-control" name="FileExcel" />
            </div>
        </div>
        @if (!Model.Correct)
        {
        <div class="row g-3">
            <div class="col-md-1">
                <a><input type="submit" value="Procesar" class="btn btn-success" /></a>
                <br />
            </div>
        </div>
        }
        else
        {
        <div class="row g-3">
            <div class="col-md-1">
                <a><input type="submit" value="Insertar" class="btn btn-success"/></a>
                <br />
            </div>
        </div>
        }
    </div>
    <br />
    }
</div>

<div class="row">
    <div class="col-md-12">
        @if (Model.Objects != null)
        {
        @if(Model.Objects.Count > 0 ){
        <table class="table table-bordered table-responsive">
            <thead>
                <tr class="text-center">
                    <td>IdRegistro</td>
                    <td>Error</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.ErrorExcel error in Model.Objects)
                {
                <tr class="text-center">
                    <td>@error.IdRegistro</td>
                    <td>@error.Mensaje</td>
                </tr>
                }
            </tbody>
        </table>
        }
        }
        else
        {
        }
    </div>
</div>


@section Scripts
{
<script src="~/lib/jquery/dist/jquery.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script type="text/javascript">

    function myFunctionTxt() {
    var x = document.getElementById("InputTxt");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}


function myFunctionExcel() {
    var x = document.getElementById("InputExcel");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}


    $('#xlsx').click(function() {
      $('#fuImage').toggle('slow', function() {
      });
    });

     $( function() {
    $( "#txt" ).datepicker();
  } );

</script>
}